#!/usr/bin/env ruby

add = ARGV[0]
device = ARGV[1]
if add.match(/^([0-9a-fA-F][0-9a-fA-F]:){5}([0-9a-fA-F][0-9a-fA-F])$/)
  if system("sudo ifconfig #{device} ether #{add}")
    puts "Succesfuly setup #{add} on #{device} device"
  end
else
  puts "Mac address is incorrect"
end
